title: Jessica Thomas - Remote Sensing Technician - MSci Environmental Science
author: Jessica Thomas 
email: j.t.thomas@exeter.ac.uk
description: this will one day be a resume for Jessica Thomas. University of Exeter Graduate and Remote Sensing Technician.

# social links
twitter_username: FallingWithJess # DO NOT include the @ character, or else the build will fail!
github_username:  jess-paige # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
